---
- name: create default site configurations
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
  notify:
    - restart nginx service
  tags:
    - configure

- name: open http port
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: open https port
  firewalld:
    service: https
    permanent: true
    state: enabled