---
# tasks file for haproxy
- name: install haproxy
  yum:
    name: haproxy
    state: installed

- include: nginx.yml
  when: hap_role == 'webserver'

- include: galera.yml
  when: hap_role == 'galera'

- name: open firewall for haproxy stats
  firewalld:
    port: '{{ ha_stats_bind_port }}'
    permanent: true
    state: enabled
    immediate: yes
  when: enable_ha_stats

- name: enable haproxy to start on boot
  service:
    name: haproxy
    state: started
    enabled: yes