---
- hosts: galera_nodes
  remote_user: kryptik
  become: yes
  become_method: sudo
  vars_prompt:
    - name: galera_root_password
      prompt: 'Enter the desired mysql root users password'
      private: yes

  roles:
    - { role: base, tags: 'base' }
    - { role: galera, tags: 'galera' }