---
- hosts: webservers
  remote_user: kryptik
  become: yes
  become_method: sudo
  roles:
    - { role: base, tags: 'base' }
    - { role: epel, tags: 'epel' }
    - { role: php7, tags: 'php7' }
    - { role: nginx, tags: 'nginx' }
