---

- name: installing nfs packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - 'nfs-utils'
    - 'python-pip'

- name: installing pexpect
  pip:
    name: pexpect

- name: SELinux boolean use_nfs_home_dirs
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes

- name: opening firewall ports
  firewalld:
    service: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 'nfs'
    - 'mountd'
    - 'rpc-bind'

- name: obtaining Kerberos ticket
  expect:
    command: 'kinit {{ ipa_principal }}'
    responses:
      (?i)password : "{{ ipa_password }}"

- name: enabling sssd with mkhomedir option
  command: 'authconfig --update --enablemkhomedir --enablesssd --enablesssdauth'

- name: running ipa-client-automount to configure nfs
  command: 'ipa-client-automount -U --location default'

- name: starting and enabling nfs services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - 'rpc-gssd'
    - 'rpcbind'
    - 'nfs-idmapd'
