---

- name: filebeat | installing filebeat
  yum:
    name: filebeat
    state: installed

- name: filebeat | starting and enabling filebeat service
  service:
    name: filebeat
    state: started
    enabled: yes

- name: filebeat | copying configuration file
  template:
    src: 'filebeat.yml.j2'
    dest: '/etc/filebeat/filebeat.yml'
    mode: 0644
  notify: restart filebeat