---

- name: metricbeat | installing metricbeat
  yum:
    name: metricbeat
    state: installed

- name: metricbeat | starting and enabling metricbeat service
  service:
    name: metricbeat
    state: started
    enabled: yes

- name: metricbeat | copying configuration file
  template:
    src: 'metricbeat.yml.j2'
    dest: '/etc/metricbeat/metricbeat.yml'
    mode: 0644
  notify: restart metricbeat
  tags: ['configure']
