---

- name: packetbeat | installing packetbeat
  yum:
    name: packetbeat
    state: installed

- name: packetbeat | copying configuration file
  template:
    src: 'packetbeat.yml.j2'
    dest: '/etc/packetbeat/packetbeat.yml'
    mode: 0644
  notify: restart packetbeat
  tags: ['configure']

- name: packetbeat | starting and enabling packetbeat service
  service:
    name: packetbeat
    state: started
    enabled: yes:q