---

# -------------- Filebeat & Metricbeat Module Checks ----------------- #
- name: checking for apache
  command: 'rpm -q httpd'
  ignore_errors: yes
  register: apache_check
- set_fact:
    mb_modules.mb_apache.enabled: True
    filebeat_modules.apache.enabled: True
  when: apache_check.stdout.find('is not installed') != -1


- name: checking for nginx
  command: 'rpm -q nginx'
  ignore_errors: yes
  register: nginx_check
- set_fact:
    mb_modules.mb_nginx.enabled: True
    filebeat_modules.nginx.enabled: True
  when: nginx_check.stdout.find('is not installed') != -1


- name: checking for mysql
  stat:
    path: '/etc/my.cnf'
  register: mysql_check
- set_fact:
    mb_modules.mb_mysql.enabled: True
    filebeat_modules.mysql.enabled: True
  when: mysql_check.stat.exists


- name: checking for auditd
  stat:
    path: '/etc/audit/auditd.conf'
  register: auditd_check
- set_fact: filebeat_modules.auditd.enabled=True
  when: auditd_check.stat.exists


# -------------- Metricbeat Module Checks ----------------- #

- name: checking for haproxy
  command: 'rpm -q haproxy'
  ignore_errors: yes
  register: haproxy_check
- set_fact: mb_modules.mb_haproxy.enabled=True
  when: haproxy_check.stdout.find('is not installed') != -1


- name: checking for php-fpm
  stat:
    path: '/etc/php-fpm.conf'
  register: php_check
- set_fact: mb_modules.mb_php_fpm.enabled=True
  when: php_check.stat.exists


- name: checking for redis
  command: 'rpm -q redis'
  ignore_errors: yes
  register: redis_check
- set_fact: mb_modules.mb_redis.enabled=True
  when: redis_check.stdout.find('is not installed') != -1


- name: checking for ceph
  stat:
    path: '/etc/systemd/system/ceph-osd.target'
  register: ceph_check
- set_fact: mb_modules.mb_ceph.enabled=True
  when: ceph_check.stat.exists


- name: checking for couchbase
  command: 'rpm -q couchbase-server'
  ignore_errors: yes
  register: couchbase_check
- set_fact: mb_modules.mb_couchbase.enabled=True
  when: couchbase_check.stdout.find('is not installed') != -1


- name: checking for docker
  stat:
    path: '/etc/sysconfig/docker'
  register: docker_check
- set_fact: mb_modules.mb_docker.enabled=True
  when: docker_check.stat.exists


- name: checking for mongod
  stat:
    path: '/etc/mongod.conf'
  register: mongod_check
- set_fact: mb_modules.mb_mongod.enabled=True
  when: mongod_check.stat.exists


- name: checking for postgresql
  command: 'rpm -q postgresql-server'
  ignore_errors: yes
  register: postgresql_check
- set_fact: mb_modules.mb_postgresql.enabled=True
  when: postgresql_check.stdout.find('is not installed') != -1


- name: checking for zookeeper
  command: 'rpm -q zookeeper'
  ignore_errors: yes
  register: zookeeper_check
- set_fact: mb_modules.mb_zoo_keeper.enabled=True
  when: zookeeper_check.stdout.find('is not installed') != -1
