---

# -------------- Filebeat & Metricbeat Module Checks ----------------- #
- name: checking for apache
  command: 'rpm -q httpd'
  ignore_errors: yes
  register: apache_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_apache': {'enabled': True }}, recursive=True) }}"
    filebeat_modules: "{{ filebeat_modules | combine({ 'apache': {'enabled': True }}, recursive=True) }}"
  when: apache_check.rc == 0


- name: checking for nginx
  command: 'rpm -q nginx'
  ignore_errors: yes
  register: nginx_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_nginx': {'enabled': True }}, recursive=True) }}"
    filebeat_modules: "{{ filebeat_modules | combine({ 'nginx': {'enabled': True }}, recursive=True) }}"
  when: nginx_check.rc == 0


- name: checking for mysql
  stat:
    path: '/usr/bin/mysql'
  register: mysql_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_mysql': {'enabled': True }}, recursive=True) }}"
    filebeat_modules: "{{ filebeat_modules | combine({ 'mysql': {'enabled': True }}, recursive=True) }}"
  when: mysql_check.stat.exists


- name: checking for auditd
  stat:
    path: '/etc/audit/auditd.conf'
  register: auditd_check
- set_fact:
    filebeat_modules: "{{ filebeat_modules | combine({ 'auditd': {'enabled': True }}, recursive=True) }}"
  when: auditd_check.stat.exists


# -------------- Metricbeat Module Checks ----------------- #

- name: checking for haproxy
  command: 'rpm -q haproxy'
  ignore_errors: yes
  register: haproxy_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_haproxy': {'enabled': True }}, recursive=True) }}"
  when: haproxy_check.rc == 0


- name: checking for php-fpm
  stat:
    path: '/etc/php-fpm.conf'
  register: php_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_php_fpm': {'enabled': True }}, recursive=True) }}"
  when: php_check.stat.exists


- name: checking for redis
  command: 'rpm -q redis'
  ignore_errors: yes
  register: redis_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_redis': {'enabled': True }}, recursive=True) }}"
  when: redis_check.rc == 0


- name: checking for ceph
  stat:
    path: '/etc/systemd/system/ceph-osd.target'
  register: ceph_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_ceph': {'enabled': True }}, recursive=True) }}"
  when: ceph_check.stat.exists


- name: checking for couchbase
  command: 'rpm -q couchbase-server'
  ignore_errors: yes
  register: couchbase_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_couchbase': {'enabled': True }}, recursive=True) }}"
  when: couchbase_check.rc == 0


- name: checking for docker
  stat:
    path: '/etc/sysconfig/docker'
  register: docker_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_docker': {'enabled': True }}, recursive=True) }}"
  when: docker_check.stat.exists


- name: checking for mongod
  stat:
    path: '/etc/mongod.conf'
  register: mongod_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_mongod': {'enabled': True }}, recursive=True) }}"
  when: mongod_check.stat.exists


- name: checking for postgresql
  command: 'rpm -q postgresql-server'
  ignore_errors: yes
  register: postgresql_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_postgresql': {'enabled': True }}, recursive=True) }}"
  when: postgresql_check.rc == 0


- name: checking for zookeeper
  command: 'rpm -q zookeeper'
  ignore_errors: yes
  register: zookeeper_check
- set_fact:
    mb_modules: "{{ mb_modules | combine({ 'mb_zoo_keeper': {'enabled': True }}, recursive=True) }}"
  when: zookeeper_check.rc == 0
