---

- name: elastic | adding elastic search repository
  copy:
    src: 'elasticsearch.repo'
    dest: '/etc/yum.repos.d/elasticsearch.repo'
    owner: root
    group: root
    mode: 0644

- name: elastic | installing elastic search packages
  yum:
    name: 'elasticsearch'
    state: present

- name: elastic | opening firewall port
  firewalld:
    port: '9200/tcp'
    permanent: true
    state: enabled
    immediate: yes

- name: elastic | installing x-pack
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack --batch
  args:
    creates: /usr/share/elasticsearch/plugins/x-pack/plugin-descriptor.properties

- name: elastic | creating ca.crt link
  file:
    path: '{{ ca_file_location }}'
    src: '{{ xpack_ldap_ca_file }}'
    owner: root
    group: elasticsearch
    mode: 0644
    state: link

- name: elastic | creating elasticsearch.yml
  template:
    src: 'elasticsearch.yml'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    owner: root
    group: elasticsearch
    mode: 0660

- name: elastic | creating x-pack role_mapping.yml
  template:
    src: 'role_mapping.yml'
    dest: '{{ xpack_ldap_role_mapping_file }}'
    owner: root
    group: elasticsearch
    mode: 0660

- name: elastic | starting and enabling elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes