---

- name: kibana | installing python-passlib
  yum:
    name: python-passlib
    state: installed
  when: kibana_nginx_enable_htpasswd

- name: kibana | creating nginx password file
  htpasswd:
    path: '{{ kibana_nginx_htpasswd_file }}'
    name: '{{ kibana_nginx_htpasswd_user }}'
    password: '{{ kibana_nginx_htpasswd_password }}'
    owner: root
    group: nginx
    mode: 0640
  when: kibana_nginx_enable_htpasswd

- name: kibana | creating nginx vhost file
  template:
    src: 'kibana-nginx.conf.j2'
    dest: "/etc/nginx/sites-available/{{ kibana_nginx_server_name }}.conf"

- name: kibana | enabling nginx vhost
  file:
    path: "/etc/nginx/sites-enabled/{{ kibana_nginx_server_name }}.conf"
    src: "/etc/nginx/sites-available/{{ kibana_nginx_server_name }}.conf"
    state: link
  notify: restart nginx
