---

- name: kibana | adding kibana repository
  copy:
    src: 'kibana.repo'
    dest: '/etc/yum.repos.d/kibana.repo'
    owner: root
    group: root
    mode: 0644

- name: kibana | installing kibana package
  yum:
    name: kibana
    state: present

- name: kibana | starting and enabling kibana service
  service:
    name: kibana
    state: started
    enabled: yes

- name: kibana | creating nginx vhost file
  template:
    src: 'kibana-nginx.conf'
    dest: "/etc/nginx/sites-available/{{ kibana_nginx_server_name }}.conf"
  when: kibana_configure_nginx

- name: kibana | enabling nginx vhost
  file:
    path: "/etc/nginx/sites-enabled/{{ kibana_nginx_server_name }}.conf"
    src: "/etc/nginx/sites-available/{{ kibana_nginx_server_name }}.conf"
    state: link
  when: kibana_configure_nginx

- name: kibana | restarting nginx
  service:
    name: nginx
    state: restarted
  when: kibana_configure_nginx