---

- name: kibana | adding kibana repository
  copy:
    src: 'kibana.repo'
    dest: '/etc/yum.repos.d/kibana.repo'
    owner: root
    group: root
    mode: 0644

- name: kibana | installing kibana package
  yum:
    name: kibana
    state: present

- include: kibana-nginx.yml
  when: kibana_configure_nginx

- name: kibana | installing x-pack
  command: /usr/share/kibana/bin/kibana-plugin install x-pack --batch
  args:
    creates: /usr/share/kibana/plugins/x-pack/index.js

- name: kibana | starting and enabling kibana service
  service:
    name: kibana
    state: started
    enabled: yes