---

- name: logstash | adding logstash repository
  copy:
    src: 'logstash.repo'
    dest: '/etc/yum.repos.d/logstash.repo'
    owner: root
    group: root
    mode: 0644

- name: logstash | installing logstash package
  yum:
    name: logstash
    state: present

- name: logstash | creating input.conf
  template:
    src: 'logstash.input.conf.j2'
    dest: '/etc/logstash/conf.d/input.conf'
    owner: root
    group: logstash
    mode: 0640
  tags: ['configure']

- name: logstash | creating output.conf
  template:
    src: 'logstash.output.conf.j2'
    dest: '/etc/logstash/conf.d/output.conf'
    owner: root
    group: logstash
    mode: 0640
  tags: ['configure']

- name: logstash | creating filter.conf
  template:
    src: 'logstash.filter.conf.j2'
    dest: '/etc/logstash/conf.d/filter.conf'
    owner: root
    group: logstash
    mode: 0640
  tags: ['configure']
  notify: restart logstash

- name: logstash | opening firewall port
  firewalld:
    port: '5044/tcp'
    permanent: true
    state: enabled
    immediate: yes

- name: logstash | set ACL for logstash group on SSL files
  acl:
    path: '{{ item }}'
    entity: logstash
    etype: group
    permissions: r
    state: present
  with_items:
    - '{{ ssl_key_path }}'
    - '{{ ssl_cert_path }}'
    - '{{ ssl_ca_path }}'

- name: logstash | installing x-pack
  logstash_plugin:
    name: x-pack
    state: present

- name: logstash | starting and enabling logstash service
  service:
    name: logstash
    state: started
    enabled: yes