---

- name: installing nfs packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - 'nfs-utils'
    - 'python-pip'

- name: installing pexpect
  pip:
    name: pexpect

- name: obtaining Kerberos ticket
  expect:
    command: 'kinit {{ ipa_principal }}'
    responses:
      (?i)password : "{{ ipa_password }}"

- name: retrieving keytab
  command: 'ipa-getkeytab -p {{ nfs_service_principal }} -k {{ keytab_location }}'

- name: opening firewall ports
  firewalld:
    service: 'nfs'
    permanent: yes
    immediate: yes
    state: enabled

- name: SELinux boolean nfs_export
  seboolean:
    name: '{{ item }}'
    state: yes
    persistent: yes
  with_items:
    - 'nfs_export_all_rw'
    - 'nfs_export_all_ro'

- name: copying exports file
  template:
    src: 'exports.j2'
    dest: '/etc/exports'
    owner: root
    group: root
    mode: 0644

- name: running exportfs
  command: 'exportfs -arv'

- name: running ipa-client-automount to configure nfs
  command: 'ipa-client-automount -U --location default'

- name: starting and enabling services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - 'nfs'
    - 'nfs-server'
    - 'nfs-secure'
    - 'nfs-secure-server'
    - 'nfs-lock'
    - 'nfs-idmap'
    - 'rpcbind'