---

- name: creating bricks directories
  file:
    name: '{{ item }}/{{ gluster_volume_name }}'
    state: directory
  with_items: '{{ gluster_bricks }}'

- name: creating gluster volume
  gluster_volume:
    state: present
    name: '{{ gluster_volume_name }}'
    bricks: '{{ gluster_bricks | join(",") }}'
    rebalance: '{{ gluster_rebalance }}'
    cluster: '{{ gluster_cluster_nodes }}'
    force: '{{ gluster_force }}'
  run_once: True

- name: starting gluster volume
  gluster_volume:
    name: '{{ gluster_volume_name }}'
    state: started
  run_once: True