---

- name: installing glusterfs packages (1/2)
  yum:
    name: '{{ gluster_release_package }}'
    state: present

- name: installing glusterfs packages (2/2)
  yum:
    name: 'glusterfs-server'
    state: present

- name: opening firewall ports
  firewalld:
    port: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - '24007-24009/tcp'
    - '49152-49160/tcp'
    - '38465-38467/tcp'
    - '111/tcp'
    - '111/udp'
    - '2049/tcp'

- name: starting and enabling glusterd
  service:
    name: glusterd
    state: started
    enabled: yes
