---
# defaults file for galera
galera_bind_address: 0.0.0.0
galera_cluster_name: 'galera_cluster'
galera_cluster_inventory_group: 'galera_nodes'
galera_master_node: '{{ groups[galera_cluster_inventory_group][0] }}'
host_has_selinux: True