---

- name: checking if host is already enrolled
  stat:
    path: '/etc/krb5.conf'
  register: krb5_stat

- name: installing ipa-client-install
  yum:
    name: 'ipa-client'
    update_cache: yes
    state: present

- name: enrolling host
  command: >
    ipa-client-install
    --unattended
    --hostname {{ ansible_hostname }}
    --server {{ ipa_server }}
    --domain {{ ipa_domain }}
    --realm {{ ipa_realm }}
    --principal {{ ipa_principal }}
    --password {{ ipa_principal_pass }}
    --ssh-trust-dns
    --mkhomedir
    --enable-dns-updates
  when: krb5_stat.stat.exists == False
