---

- name: install base packages on all hosts
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - 'policycoreutils-python'
    - 'libselinux-python'
    - 'libsemanage-python'
  tags: ['install']

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: ['install', 'update']